name = input("Enter your name: ")
age = input("Enter your age: ")
question = input("What is the best subject in the world?")
print("Your name is " + name + " and you are " + age + " years of age.")
print("The best subject in the world is... ")
